name: builder
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dependencies:
    path: ../shared/dependencies
  core:
    path: ../core
  home:
    path: ../modules/home
  login:
    path: ../modules/login
  sales:
    path: ../modules/sales
  apod:
    path: ../modules/apod
  digital_account:
    path: ../shared/services/digital_account
  network_services:
    path: ../shared/services/network_services
  # modular_release_guard:
  #   path: c:/projetos/modular_release_guard
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

scripts:
  getall: flutter pub get & cd ../shared/dependencies & flutter pub get & cd ../shared/services/digital_account & flutter pub get & cd ../modules/home & flutter pub get & cd ../modules/login & flutter pub get & cd ../modules/sales & flutter pub get
  test_error: flutter pub get2
  print: echo $name
vars:
  name: jacob
